services:
  ####################################################
  # MINIO NÓ 1
  ####################################################
  minio1:
    image: minio/minio:latest
    container_name: minio1
    hostname: minio1
    volumes:
      - minio1_data1:/data1
      - minio1_data2:/data2
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    expose:
      - "9000"
      - "9090"
    networks:
      - minio_net
    command: >
      server
      --address :9000
      --console-address :9090
      http://minio1/data1
      http://minio1/data2
      http://minio2/data1
      http://minio2/data2
      http://minio3/data1
      http://minio3/data2
      http://minio4/data1
      http://minio4/data2

  ####################################################
  # MINIO NÓ 2
  ####################################################
  minio2:
    image: minio/minio:latest
    container_name: minio2
    hostname: minio2
    volumes:
      - minio2_data1:/data1
      - minio2_data2:/data2
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    expose:
      - "9000"
      - "9090"
    networks:
      - minio_net
    command: >
      server
      --address :9000
      --console-address :9090
      http://minio1/data1
      http://minio1/data2
      http://minio2/data1
      http://minio2/data2
      http://minio3/data1
      http://minio3/data2
      http://minio4/data1
      http://minio4/data2

  ####################################################
  # MINIO NÓ 3
  ####################################################
  minio3:
    image: minio/minio:latest
    container_name: minio3
    hostname: minio3
    volumes:
      - minio3_data1:/data1
      - minio3_data2:/data2
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    expose:
      - "9000"
      - "9090"
    networks:
      - minio_net
    command: >
      server
      --address :9000
      --console-address :9090
      http://minio1/data1
      http://minio1/data2
      http://minio2/data1
      http://minio2/data2
      http://minio3/data1
      http://minio3/data2
      http://minio4/data1
      http://minio4/data2

  ####################################################
  # MINIO NÓ 4                                       # 
  ####################################################
  minio4:
    image: minio/minio:latest
    container_name: minio4
    hostname: minio4
    volumes:
      - minio4_data1:/data1
      - minio4_data2:/data2
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    expose:
      - "9000"
      - "9090"
    networks:
      - minio_net
    command: >
      server
      --address :9000
      --console-address :9090
      http://minio1/data1
      http://minio1/data2
      http://minio2/data1
      http://minio2/data2
      http://minio3/data1
      http://minio3/data2
      http://minio4/data1
      http://minio4/data2

  ####################################################
  # NGINX - Para balancear e expor um único endpoint #
  ####################################################
  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    ports:
      - "9000:9000"   # Proxy S3 -> Todos os nós
      - "9090:9090"   # Proxy Console -> Todos os nós
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - minio_net

networks:
  minio_net:

volumes:
  minio1_data1:
  minio1_data2:
  minio2_data1:
  minio2_data2:
  minio3_data1:
  minio3_data2:
  minio4_data1:
  minio4_data2:
